[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
remappings = [
    "hardhat/=node_modules/hardhat/",
    "xdeployer/=node_modules/xdeployer/",
    "forge-std/=contracts/lib/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
